<?php
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Start output buffering
ob_start();

// Handle CORS (credentialed, dynamic Origin)
$origin = isset($_SERVER['HTTP_ORIGIN']) ? $_SERVER['HTTP_ORIGIN'] : '';
if ($origin) {
    header("Access-Control-Allow-Origin: $origin");
    header('Vary: Origin');
} else {
    // Fallback for direct requests
    header('Access-Control-Allow-Origin: http://localhost');
}
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Methods: POST, GET, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, X-Requested-With');
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    ob_clean();
    exit(0);
}

require_once __DIR__ . '/../config/database.php';

$method = $_SERVER['REQUEST_METHOD'];
$action = $_GET['action'] ?? '';

try {
    switch ($action) {
        case 'login':
            handleLogin($pdo);
            break;
        case 'signup':
            handleSignup($pdo);
            break;
        case 'logout':
            handleLogout();
            break;
        case 'check_session':
            checkSession();
            break;
        default:
            sendError('Invalid action');
    }
} catch (Exception $e) {
    ob_clean();
    sendError('Server error: ' . $e->getMessage(), 500);
}

function handleSignup($pdo) {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        sendError('Method not allowed');
    }
    $data = json_decode(file_get_contents('php://input'), true);
    if (!$data) {
        sendError('Invalid JSON data');
    }
    $required_fields = ['name', 'email', 'mobile', 'password'];
    foreach ($required_fields as $field) {
        if (!isset($data[$field]) || empty(trim($data[$field]))) {
            sendError("Field '$field' is required");
        }
    }
    $name = trim($data['name']);
    $email = trim($data['email']);
    $mobile = trim($data['mobile']);
    $password = password_hash($data['password'], PASSWORD_DEFAULT);
    // Check if email already exists
    $stmt = $pdo->prepare("SELECT id FROM users WHERE email = ?");
    $stmt->execute([$email]);
    if ($stmt->fetch()) {
        sendError('Email already registered');
    }
    // Insert user
    $stmt = $pdo->prepare("INSERT INTO users (name, email, mobile, password) VALUES (?, ?, ?, ?)");
    $stmt->execute([$name, $email, $mobile, $password]);
    sendSuccess(['user_id' => $pdo->lastInsertId()], 'Registration successful');
}

function handleLogin($pdo) {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        sendError('Method not allowed');
    }
    $data = json_decode(file_get_contents('php://input'), true);
    if (!$data) {
        sendError('Invalid JSON data');
    }
    if (!isset($data['email']) || !isset($data['password'])) {
        sendError('Email and password are required');
    }
    $email = trim($data['email']);
    $password = $data['password'];
    $stmt = $pdo->prepare("SELECT id, name, email, password FROM users WHERE email = ?");
    $stmt->execute([$email]);
    $user = $stmt->fetch();
    if ($user && password_verify($password, $user['password'])) {
        session_start();
        $_SESSION['user_id'] = $user['id'];
        $_SESSION['user_name'] = $user['name'];
        $_SESSION['user_email'] = $user['email'];
        sendSuccess(['user_id' => $user['id'], 'name' => $user['name'], 'email' => $user['email']], 'Login successful');
    } else {
        sendError('Invalid email or password');
    }
}

function handleLogout() {
    session_start();
    session_destroy();
    ob_clean();
    sendSuccess([], 'Logout successful');
}

function checkSession() {
    session_start();
    if (!isset($_SESSION['user_id'])) {
        sendError('No active session', 401);
    }
    ob_clean();
    sendSuccess([
        'user_id' => $_SESSION['user_id'],
        'name' => $_SESSION['user_name'] ?? 'User',
        'email' => $_SESSION['user_email'] ?? ''
    ], 'Session valid');
}

function sendResponse($data, $status = 200) {
    http_response_code($status);
    header('Content-Type: application/json');
    echo json_encode($data);
    exit;
}
function sendError($message, $status = 400) {
    sendResponse(['error' => $message], $status);
}
function sendSuccess($data, $message = 'Success') {
    sendResponse(['success' => true, 'message' => $message, 'data' => $data]);
}
// Fallback: If nothing was sent, always return a JSON error
if (ob_get_length() === 0) {
    header('Content-Type: application/json');
    http_response_code(500);
    echo json_encode(['error' => 'No response generated by server']);
    exit;
}
